POST http://localhost:5000/api/trainings/2/registration
Content-Type: application/json

{
   "firstName": "Inna",
   "lastName": "Zarechna",
   "email": "nanovika2@fmail.com"
}

###
GET http://localhost:5000/api/users/11/trainings

###
DELETE http://localhost:5000/api/users/11/trainings
Content-Type: application/json

{
   "trainingId": 1
}